export const FONT_FAMILY = {
    // Inter
    "Inter-Black": require("../../assets/fonts/Inter_18pt-Black.ttf"),
    "Inter-BlackItalic": require("../../assets/fonts/Inter_18pt-BlackItalic.ttf"),
    "Inter-Bold": require("../../assets/fonts/Inter_18pt-Bold.ttf"),
    "Inter-BoldItalic": require("../../assets/fonts/Inter_18pt-BoldItalic.ttf"),
    "Inter-ExtraBold": require("../../assets/fonts/Inter_18pt-ExtraBold.ttf"),
    "Inter-ExtraBoldItalic": require("../../assets/fonts/Inter_18pt-ExtraBoldItalic.ttf"),
    "Inter-ExtraLight": require("../../assets/fonts/Inter_18pt-ExtraLight.ttf"),
    "Inter-ExtraLightItalic": require("../../assets/fonts/Inter_18pt-ExtraLightItalic.ttf"),
    "Inter-Italic": require("../../assets/fonts/Inter_18pt-Italic.ttf"),
    "Inter-Light": require("../../assets/fonts/Inter_18pt-Light.ttf"),
    "Inter-LightItalic": require("../../assets/fonts/Inter_18pt-LightItalic.ttf"),
    "Inter-Medium": require("../../assets/fonts/Inter_18pt-Medium.ttf"),
    "Inter-MediumItalic": require("../../assets/fonts/Inter_18pt-MediumItalic.ttf"),
    "Inter-Regular": require("../../assets/fonts/Inter_18pt-Regular.ttf"),
    "Inter-SemiBold": require("../../assets/fonts/Inter_18pt-SemiBold.ttf"),
    "Inter-SemiBoldItalic": require("../../assets/fonts/Inter_18pt-SemiBoldItalic.ttf"),
    "Inter-Thin": require("../../assets/fonts/Inter_18pt-Thin.ttf"),
    "Inter-ThinItalic": require("../../assets/fonts/Inter_18pt-ThinItalic.ttf"),

    // Plus Jakarta Sans
    "PlusJakartaSans-Regular": require("../../assets/fonts/PlusJakartaSans-Regular.ttf"),
    "PlusJakartaSans-Bold": require("../../assets/fonts/PlusJakartaSans-Bold.ttf"),
    "PlusJakartaSans-BoldItalic": require("../../assets/fonts/PlusJakartaSans-BoldItalic.ttf"),
    "PlusJakartaSans-ExtraBold": require("../../assets/fonts/PlusJakartaSans-ExtraBold.ttf"),
    "PlusJakartaSans-ExtraBoldItalic": require("../../assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf"),
    "PlusJakartaSans-ExtraLight": require("../../assets/fonts/PlusJakartaSans-ExtraLight.ttf"),
    "PlusJakartaSans-ExtraLightItalic": require("../../assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf"),
    "PlusJakartaSans-Italic": require("../../assets/fonts/PlusJakartaSans-Italic.ttf"),
    "PlusJakartaSans-Light": require("../../assets/fonts/PlusJakartaSans-Light.ttf"),
    "PlusJakartaSans-LightItalic": require("../../assets/fonts/PlusJakartaSans-LightItalic.ttf"),
    "PlusJakartaSans-Medium": require("../../assets/fonts/PlusJakartaSans-Medium.ttf"),
    "PlusJakartaSans-MediumItalic": require("../../assets/fonts/PlusJakartaSans-MediumItalic.ttf"),
    "PlusJakartaSans-SemiBold": require("../../assets/fonts/PlusJakartaSans-SemiBold.ttf"),
    "PlusJakartaSans-SemiBoldItalic": require("../../assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf"),
};
