export const AppRoutes = {
    MAIN: '/',
    HOME: 'Home',
    LOGIN: 'Login',
    REGISTER: 'Register',
    PROFILE: 'Profile',
    SETTINGS: 'Settings',
    ONBOARDING: 'Onboarding',
    AUTH: 'Auth',
    PASSWORD_RECOVERY: 'Password_recovery',
    VALIDATION_CODE: 'Validation_Code',
    RESET_PASSWORD: 'Reset_Password',
    SUCESS_REGISTER: 'Sucess_Register',
    INTERPRISE_DATA_REGISTER: 'Interprise_Register',
};
